config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/speakers', to: 'static_pages#speakers'
  get  '/reviews',    to: 'static_pages#reviews'
  get  '/music',   to: 'static_pages#music'
  get  '/mixers', to: 'static_pages#mixers'
  get '/miscellaneous',    to: 'static_pages#miscellaneous'
  get  '/membership',   to: 'static_pages#membership'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  
  
  
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
      <ul>
 <li><a><%= link_to "Home",    root_path %></a></li>
  <li><a><%= link_to "About Us",    about_path %></a></li>
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Equipment</a>
            <div class="dropdown-content">
                  <a><%= link_to "Music",  music_path %></a>
                  <a><%= link_to "Mixers", mixers_path %></a>
                  <a><%= link_to "speakers",speakers_path %></a>
                  <a><%= link_to "Miscellaneous", miscellaneous_path %></a>
            </div>
     </li>
     <li><a><%= link_to "Membership",membership_path %></a></li>
     <li><a><%= link_to "Reviews",reviews_path %></a></li>
     
     <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
              <% else %>
              <li><%= link_to "Log in", login_path %></li>
              <% end %>
            </ul>
          </li>
    </ul>
    
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | VibeCity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
       <%= render 'layouts/footer' %>
       <%= image_tag 'vibecity.jpg', width: 20, height: 20, alt: 'grinder'%>
      <%= yield %>
    </div>

</body>
</html>